# Generated by Django 3.2.25 on 2024-10-14 13:22

from django.db import migrations
import rest_hooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_hooks', '0002_swappable_hook_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='authorization_token',
            field=rest_hooks.models.EncryptedTextField(blank=True, max_length=255, null=True, verbose_name='Auth token'),
        ),
    ]
